import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "./src/schema/index.js";

const { Pool } = pg;

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL not set");

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

const { usersTable, sellersTable, productsTable, ordersTable, walletsTable, notificationsTable } = schema;

async function seed() {
  console.log("🌱 Seeding database...");

  // Clear existing data
  await db.delete(notificationsTable);
  await db.delete(ordersTable);
  await db.delete(productsTable);
  await db.delete(walletsTable);
  await db.delete(sellersTable);
  await db.delete(usersTable);

  // Users
  const users = [
    { id: "user-admin-1", name: "Admin User", phone: "01700000001", email: "admin@paikarmart.com", role: "admin" as const, district: "Dhaka", area: "Motijheel" },
    { id: "user-seller-1", name: "Rahman Hossain", phone: "01700000002", email: "rahman@paikarmart.com", role: "seller" as const, district: "Dhaka", area: "Mirpur" },
    { id: "user-seller-2", name: "Fatema Begum", phone: "01700000003", email: "fatema@paikarmart.com", role: "seller" as const, district: "Dhaka", area: "Gulshan" },
    { id: "user-seller-3", name: "Karim Mia", phone: "01700000004", email: "karim@paikarmart.com", role: "seller" as const, district: "Chittagong", area: "Agrabad" },
    { id: "user-seller-4", name: "Nasrin Akter", phone: "01700000005", email: "nasrin@paikarmart.com", role: "seller" as const, district: "Sylhet", area: "Zindabazar" },
    { id: "user-seller-5", name: "Alam Trading", phone: "01700000006", email: "alam@paikarmart.com", role: "seller" as const, district: "Rajshahi", area: "Shaheb Bazar" },
    { id: "user-buyer-1", name: "Siddik Munna", phone: "01811111111", email: "siddik@gmail.com", role: "buyer" as const, district: "Dhaka", area: "Dhanmondi" },
    { id: "user-buyer-2", name: "Taslima Khatun", phone: "01822222222", email: "taslima@gmail.com", role: "buyer" as const, district: "Dhaka", area: "Banani" },
    { id: "user-buyer-3", name: "Mizan Rahman", phone: "01833333333", email: "mizan@gmail.com", role: "buyer" as const, district: "Chittagong", area: "Nasirabad" },
    { id: "user-buyer-4", name: "Runa Akter", phone: "01844444444", email: "runa@gmail.com", role: "buyer" as const, district: "Sylhet", area: "Upashahar" },
  ];
  await db.insert(usersTable).values(users);
  console.log(`✅ Inserted ${users.length} users`);

  // Sellers
  const sellers = [
    {
      id: "seller-1",
      shopName: "Rahman Electronics",
      businessType: "retailer" as const,
      status: "active" as const,
      phone: "01700000002",
      email: "rahman@paikarmart.com",
      address: "Shop 12, Mirpur-1, Dhaka",
      location: "Dhaka",
      district: "Dhaka",
      rating: 4.8,
      totalProducts: 45,
      totalSales: 120000,
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&q=80",
      description: "Official electronics dealer. All products with warranty.",
      deliveryTypes: ["seller_delivery", "platform_delivery"],
      coverageAreas: ["Dhaka", "Chittagong", "Sylhet"],
    },
    {
      id: "seller-2",
      shopName: "Dhaka Fashion House",
      businessType: "brand_seller" as const,
      status: "active" as const,
      phone: "01700000003",
      email: "fatema@paikarmart.com",
      address: "Level 3, Bashundhara City, Gulshan",
      location: "Dhaka",
      district: "Dhaka",
      rating: 4.6,
      totalProducts: 220,
      totalSales: 350000,
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80",
      description: "Premium fashion brand — ethnic and western wear.",
      deliveryTypes: ["platform_delivery"],
      coverageAreas: ["Dhaka", "Rajshahi"],
    },
    {
      id: "seller-3",
      shopName: "CTG Wholesale Hub",
      businessType: "wholesaler" as const,
      status: "active" as const,
      phone: "01700000004",
      email: "karim@paikarmart.com",
      address: "Agrabad Commercial Area, Chittagong",
      location: "Chittagong",
      district: "Chittagong",
      rating: 4.5,
      totalProducts: 180,
      totalSales: 800000,
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=300&q=80",
      description: "Bangladesh's largest wholesale hub for all goods.",
      deliveryTypes: ["seller_delivery", "local_delivery"],
      coverageAreas: ["Chittagong", "Cox's Bazar", "Comilla"],
    },
    {
      id: "seller-4",
      shopName: "Sylhet Organic Farm",
      businessType: "local_shop" as const,
      status: "active" as const,
      phone: "01700000005",
      email: "nasrin@paikarmart.com",
      address: "Zindabazar, Sylhet",
      location: "Sylhet",
      district: "Sylhet",
      rating: 4.9,
      totalProducts: 35,
      totalSales: 95000,
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&q=80",
      description: "Fresh organic produce directly from the farm.",
      deliveryTypes: ["seller_delivery"],
      coverageAreas: ["Sylhet", "Moulvibazar"],
    },
    {
      id: "seller-5",
      shopName: "Rajshahi Mango Mart",
      businessType: "local_shop" as const,
      status: "active" as const,
      phone: "01700000006",
      email: "alam@paikarmart.com",
      address: "Shaheb Bazar, Rajshahi",
      location: "Rajshahi",
      district: "Rajshahi",
      rating: 4.7,
      totalProducts: 28,
      totalSales: 65000,
      image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=300&q=80",
      description: "Famous Rajshahi Himsagar & Langra mango. Season-based shipping.",
      deliveryTypes: ["platform_delivery", "pickup"],
      coverageAreas: ["Rajshahi", "Naogaon", "Chapainawabganj"],
    },
  ];
  await db.insert(sellersTable).values(sellers);
  console.log(`✅ Inserted ${sellers.length} sellers`);

  // Products
  const products = [
    {
      id: "prod-1",
      name: "Samsung Galaxy A55 5G",
      category: "Electronics",
      subcategory: "Smartphones",
      type: "physical" as const,
      price: 42500,
      costPrice: 38000,
      stock: 25,
      moq: 1,
      description: "Samsung Galaxy A55 5G — 12GB RAM, 256GB, Official Bangladesh warranty 1 year.",
      images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.7,
      reviewCount: 128,
      inStock: true,
      deliveryDays: "1-3 days",
    },
    {
      id: "prod-2",
      name: "Apple iPhone 15 — 128GB",
      category: "Electronics",
      subcategory: "Smartphones",
      type: "physical" as const,
      price: 115000,
      costPrice: 108000,
      stock: 10,
      moq: 1,
      description: "Apple iPhone 15 128GB, official warranty. Dynamic Island, 48MP camera.",
      images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.9,
      reviewCount: 214,
      inStock: true,
      deliveryDays: "1-2 days",
    },
    {
      id: "prod-3",
      name: "Exclusive Muslin Sharee — Handloom",
      category: "Fashion",
      subcategory: "Women's Clothing",
      type: "physical" as const,
      price: 3800,
      costPrice: 2500,
      stock: 50,
      moq: 1,
      description: "Pure muslin handloom sharee. Perfect for weddings and festivals. Custom color orders accepted.",
      images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80"],
      vendorId: "seller-2",
      vendorName: "Dhaka Fashion House",
      location: "Dhaka",
      rating: 4.8,
      reviewCount: 87,
      inStock: true,
      deliveryDays: "2-4 days",
    },
    {
      id: "prod-4",
      name: "Men's Panjabi — Eid Collection",
      category: "Fashion",
      subcategory: "Men's Clothing",
      type: "physical" as const,
      price: 1850,
      costPrice: 1200,
      stock: 80,
      moq: 3,
      description: "Premium cotton panjabi for Eid. Available in 12 colors, all sizes.",
      images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80"],
      vendorId: "seller-2",
      vendorName: "Dhaka Fashion House",
      location: "Dhaka",
      rating: 4.5,
      reviewCount: 203,
      inStock: true,
      deliveryDays: "2-3 days",
    },
    {
      id: "prod-5",
      name: "Rice (Miniket) — 50kg Bag",
      category: "Grocery",
      subcategory: "Rice & Grain",
      type: "physical" as const,
      price: 3200,
      costPrice: 2800,
      stock: 200,
      moq: 5,
      description: "Premium Miniket rice, 50kg sack. Best quality from Noakhali.",
      images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80"],
      vendorId: "seller-3",
      vendorName: "CTG Wholesale Hub",
      location: "Chittagong",
      rating: 4.6,
      reviewCount: 341,
      inStock: true,
      deliveryDays: "3-5 days",
    },
    {
      id: "prod-6",
      name: "Soybean Oil — 5L Bottle",
      category: "Grocery",
      subcategory: "Edible Oil",
      type: "physical" as const,
      price: 890,
      costPrice: 780,
      stock: 500,
      moq: 10,
      description: "Pure soybean cooking oil, 5L. Bulk wholesale available.",
      images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80"],
      vendorId: "seller-3",
      vendorName: "CTG Wholesale Hub",
      location: "Chittagong",
      rating: 4.4,
      reviewCount: 156,
      inStock: true,
      deliveryDays: "2-4 days",
    },
    {
      id: "prod-7",
      name: "Organic Turmeric Powder — 500g",
      category: "Grocery",
      subcategory: "Spices",
      type: "physical" as const,
      price: 280,
      costPrice: 180,
      stock: 300,
      moq: 1,
      description: "100% organic turmeric from Sylhet highlands. No additives.",
      images: ["https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&q=80"],
      vendorId: "seller-4",
      vendorName: "Sylhet Organic Farm",
      location: "Sylhet",
      rating: 4.9,
      reviewCount: 89,
      inStock: true,
      deliveryDays: "3-5 days",
    },
    {
      id: "prod-8",
      name: "Fresh Hilsa Fish — 1kg",
      category: "Grocery",
      subcategory: "Fish & Seafood",
      type: "physical" as const,
      price: 1200,
      costPrice: 900,
      stock: 50,
      moq: 1,
      description: "Fresh Padma Hilsa, direct from fishermen. Chilled delivery.",
      images: ["https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&q=80"],
      vendorId: "seller-4",
      vendorName: "Sylhet Organic Farm",
      location: "Sylhet",
      rating: 4.7,
      reviewCount: 62,
      inStock: true,
      deliveryDays: "1-2 days",
    },
    {
      id: "prod-9",
      name: "Himsagar Mango — 5kg Box",
      category: "Grocery",
      subcategory: "Fruits",
      type: "physical" as const,
      price: 750,
      costPrice: 500,
      stock: 100,
      moq: 2,
      description: "Premium Rajshahi Himsagar mango, 5kg gift box. Seasonal product.",
      images: ["https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80"],
      vendorId: "seller-5",
      vendorName: "Rajshahi Mango Mart",
      location: "Rajshahi",
      rating: 4.8,
      reviewCount: 178,
      inStock: true,
      deliveryDays: "2-3 days",
    },
    {
      id: "prod-10",
      name: "Langra Mango — 10kg",
      category: "Grocery",
      subcategory: "Fruits",
      type: "physical" as const,
      price: 1400,
      costPrice: 950,
      stock: 80,
      moq: 1,
      description: "Rajshahi Langra mango, 10kg bulk. Best taste guaranteed.",
      images: ["https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80"],
      vendorId: "seller-5",
      vendorName: "Rajshahi Mango Mart",
      location: "Rajshahi",
      rating: 4.9,
      reviewCount: 234,
      inStock: true,
      deliveryDays: "2-3 days",
    },
    {
      id: "prod-11",
      name: "Redmi Note 13 Pro — 8GB/256GB",
      category: "Electronics",
      subcategory: "Smartphones",
      type: "physical" as const,
      price: 28500,
      costPrice: 25000,
      stock: 30,
      moq: 1,
      description: "Xiaomi Redmi Note 13 Pro, 200MP camera, 5000mAh battery. Global version.",
      images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.6,
      reviewCount: 95,
      inStock: true,
      deliveryDays: "1-3 days",
    },
    {
      id: "prod-12",
      name: "Dell Inspiron 15 Laptop",
      category: "Electronics",
      subcategory: "Laptops",
      type: "physical" as const,
      price: 65000,
      costPrice: 58000,
      stock: 8,
      moq: 1,
      description: "Dell Inspiron 15, Intel Core i5, 16GB RAM, 512GB SSD. Official warranty.",
      images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.5,
      reviewCount: 43,
      inStock: true,
      deliveryDays: "2-4 days",
    },
    {
      id: "prod-13",
      name: "Women's Kurti Set — Summer",
      category: "Fashion",
      subcategory: "Women's Clothing",
      type: "physical" as const,
      price: 950,
      costPrice: 620,
      stock: 150,
      moq: 2,
      description: "Stylish cotton kurti set, ideal for summer. Multiple designs.",
      images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80"],
      vendorId: "seller-2",
      vendorName: "Dhaka Fashion House",
      location: "Dhaka",
      rating: 4.6,
      reviewCount: 312,
      inStock: true,
      deliveryDays: "1-3 days",
    },
    {
      id: "prod-14",
      name: "Wholesale Sugar — 50kg Sack",
      category: "Grocery",
      subcategory: "Sugar & Sweeteners",
      type: "physical" as const,
      price: 4500,
      costPrice: 4100,
      stock: 300,
      moq: 10,
      description: "Refined white sugar, 50kg. Best for wholesale buyers and restaurants.",
      images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&q=80"],
      vendorId: "seller-3",
      vendorName: "CTG Wholesale Hub",
      location: "Chittagong",
      rating: 4.3,
      reviewCount: 67,
      inStock: true,
      deliveryDays: "3-5 days",
    },
    {
      id: "prod-15",
      name: "Wireless Bluetooth Headphone",
      category: "Electronics",
      subcategory: "Audio",
      type: "physical" as const,
      price: 2800,
      costPrice: 2100,
      stock: 45,
      moq: 1,
      description: "Premium wireless headphone, 30hr battery, ANC. Universal compatibility.",
      images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.5,
      reviewCount: 156,
      inStock: true,
      deliveryDays: "1-2 days",
    },
    {
      id: "prod-16",
      name: "Organic Black Tea — 250g",
      category: "Grocery",
      subcategory: "Tea & Coffee",
      type: "physical" as const,
      price: 320,
      costPrice: 210,
      stock: 200,
      moq: 1,
      description: "Premium Sylhet CTC black tea. Rich flavor, direct from garden.",
      images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80"],
      vendorId: "seller-4",
      vendorName: "Sylhet Organic Farm",
      location: "Sylhet",
      rating: 4.8,
      reviewCount: 198,
      inStock: true,
      deliveryDays: "2-3 days",
    },
    {
      id: "prod-17",
      name: "Smart Watch — Pro Series",
      category: "Electronics",
      subcategory: "Wearables",
      type: "physical" as const,
      price: 4500,
      costPrice: 3500,
      stock: 20,
      moq: 1,
      description: "Smartwatch with health monitoring, GPS, AMOLED display. 7 days battery.",
      images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.4,
      reviewCount: 72,
      inStock: true,
      deliveryDays: "1-3 days",
    },
    {
      id: "prod-18",
      name: "Salwar Kameez — Embroidered",
      category: "Fashion",
      subcategory: "Women's Clothing",
      type: "physical" as const,
      price: 2200,
      costPrice: 1500,
      stock: 65,
      moq: 1,
      description: "Hand-embroidered salwar kameez. Festive collection. Sizes S to XXL.",
      images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80"],
      vendorId: "seller-2",
      vendorName: "Dhaka Fashion House",
      location: "Dhaka",
      rating: 4.7,
      reviewCount: 133,
      inStock: true,
      deliveryDays: "2-3 days",
    },
    {
      id: "prod-19",
      name: "Website Development Service",
      category: "Services",
      subcategory: "Digital Services",
      type: "service" as const,
      priceOnInquiry: true,
      stock: 999,
      moq: 1,
      description: "Full-stack website development — React, Node, Laravel. 30-day delivery.",
      images: ["https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&q=80"],
      vendorId: "seller-1",
      vendorName: "Rahman Electronics",
      location: "Dhaka",
      rating: 4.9,
      reviewCount: 28,
      inStock: true,
      deliveryDays: "15-30 days",
    },
    {
      id: "prod-20",
      name: "Home AC 1.5 Ton — Inverter",
      category: "Electronics",
      subcategory: "Home Appliances",
      type: "physical" as const,
      price: 58000,
      costPrice: 52000,
      stock: 15,
      moq: 1,
      description: "Energy-efficient 1.5 ton inverter AC. 5 star rating. Free installation.",
      images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80"],
      vendorId: "seller-3",
      vendorName: "CTG Wholesale Hub",
      location: "Chittagong",
      rating: 4.6,
      reviewCount: 54,
      inStock: true,
      deliveryDays: "3-7 days",
    },
  ];
  await db.insert(productsTable).values(products);
  console.log(`✅ Inserted ${products.length} products`);

  // Sample orders
  const orders = [
    {
      id: "order-1",
      userId: "user-buyer-1",
      items: [{ productId: "prod-1", productName: "Samsung Galaxy A55 5G", quantity: 1, price: 42500, subtotal: 42500, vendorId: "seller-1", vendorName: "Rahman Electronics" }],
      status: "completed" as const,
      deliveryType: "platform_delivery" as const,
      paymentMethod: "cash_on_delivery",
      totalAmount: 42500,
      deliveryCharge: 100,
      trackingCode: "PM-2026-001",
      estimatedDelivery: "2026-04-28",
      customerName: "Siddik Munna",
      customerPhone: "01811111111",
      customerAddress: "House 5, Road 3, Dhanmondi, Dhaka",
      district: "Dhaka",
      area: "Dhanmondi",
    },
    {
      id: "order-2",
      userId: "user-buyer-1",
      items: [{ productId: "prod-3", productName: "Exclusive Muslin Sharee", quantity: 2, price: 3800, subtotal: 7600, vendorId: "seller-2", vendorName: "Dhaka Fashion House" }],
      status: "shipped" as const,
      deliveryType: "seller_delivery" as const,
      paymentMethod: "bkash",
      totalAmount: 7600,
      deliveryCharge: 60,
      trackingCode: "PM-2026-002",
      estimatedDelivery: "2026-05-03",
      customerName: "Siddik Munna",
      customerPhone: "01811111111",
      customerAddress: "House 5, Road 3, Dhanmondi, Dhaka",
      district: "Dhaka",
      area: "Dhanmondi",
    },
    {
      id: "order-3",
      userId: "user-buyer-2",
      items: [{ productId: "prod-9", productName: "Himsagar Mango 5kg", quantity: 3, price: 750, subtotal: 2250, vendorId: "seller-5", vendorName: "Rajshahi Mango Mart" }],
      status: "processing" as const,
      deliveryType: "platform_delivery" as const,
      paymentMethod: "nagad",
      totalAmount: 2250,
      deliveryCharge: 80,
      trackingCode: "PM-2026-003",
      estimatedDelivery: "2026-05-05",
      customerName: "Taslima Khatun",
      customerPhone: "01822222222",
      customerAddress: "Flat 4B, Banani, Dhaka",
      district: "Dhaka",
      area: "Banani",
    },
    {
      id: "order-4",
      userId: "user-buyer-3",
      items: [
        { productId: "prod-7", productName: "Organic Turmeric Powder", quantity: 5, price: 280, subtotal: 1400, vendorId: "seller-4", vendorName: "Sylhet Organic Farm" },
        { productId: "prod-16", productName: "Organic Black Tea", quantity: 3, price: 320, subtotal: 960, vendorId: "seller-4", vendorName: "Sylhet Organic Farm" },
      ],
      status: "confirmed" as const,
      deliveryType: "seller_delivery" as const,
      paymentMethod: "cash_on_delivery",
      totalAmount: 2360,
      deliveryCharge: 120,
      trackingCode: "PM-2026-004",
      estimatedDelivery: "2026-05-06",
      customerName: "Mizan Rahman",
      customerPhone: "01833333333",
      customerAddress: "House 22, Nasirabad, Chittagong",
      district: "Chittagong",
      area: "Nasirabad",
    },
  ];
  await db.insert(ordersTable).values(orders);
  console.log(`✅ Inserted ${orders.length} orders`);

  // Wallets
  const wallets = [
    {
      userId: "user-buyer-1",
      balance: 1250.50,
      totalEarned: 3200.75,
      investmentValue: 5000.00,
      transactions: [
        { id: "txn-1", type: "reward", amount: 425, description: "Cashback on Samsung purchase", createdAt: new Date("2026-04-28").toISOString() },
        { id: "txn-2", type: "reward", amount: 76, description: "Cashback on Sharee purchase", createdAt: new Date("2026-04-30").toISOString() },
        { id: "txn-3", type: "adjustment", amount: -500, description: "Withdrawal to bKash", createdAt: new Date("2026-04-25").toISOString() },
        { id: "txn-4", type: "reward", amount: 50, description: "Referral bonus", createdAt: new Date("2026-04-20").toISOString() },
      ],
    },
    {
      userId: "user-buyer-2",
      balance: 320.00,
      totalEarned: 650.00,
      investmentValue: 0,
      transactions: [
        { id: "txn-5", type: "reward", amount: 22.50, description: "Cashback on mango order", createdAt: new Date("2026-05-01").toISOString() },
      ],
    },
    {
      userId: "user-admin-1",
      balance: 50000,
      totalEarned: 120000,
      investmentValue: 200000,
      transactions: [],
    },
  ];
  await db.insert(walletsTable).values(wallets);
  console.log(`✅ Inserted ${wallets.length} wallets`);

  // Notifications
  const notifications = [
    {
      id: "notif-1",
      userId: "user-buyer-1",
      type: "order" as const,
      title: "Order Delivered!",
      message: "Your Samsung Galaxy A55 5G has been delivered. Enjoy!",
      read: true,
    },
    {
      id: "notif-2",
      userId: "user-buyer-1",
      type: "delivery" as const,
      title: "Order Shipped",
      message: "Your Muslin Sharee order is on the way. Tracking: PM-2026-002",
      read: false,
    },
    {
      id: "notif-3",
      userId: "user-buyer-1",
      type: "account" as const,
      title: "Welcome to PaikarMart!",
      message: "Your account has been created. Enjoy shopping!",
      read: true,
    },
    {
      id: "notif-4",
      userId: "user-buyer-2",
      type: "order" as const,
      title: "Order Confirmed",
      message: "Your mango order has been confirmed. Expected delivery: May 5.",
      read: false,
    },
  ];
  await db.insert(notificationsTable).values(notifications);
  console.log(`✅ Inserted ${notifications.length} notifications`);

  console.log("\n✅ Database seeded successfully!");
  await pool.end();
}

seed().catch((err) => {
  console.error("❌ Seed error:", err);
  process.exit(1);
});
